version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: 'true'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka_data:/var/lib/kafka/data

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  

  app:
    build: ./analytics-api
    container_name: api
    ports:
      - "8435:8435"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_TOPIC: users
      SQL_HOST: db
      SQL_USER: root
      SQL_PASSWORD: password
      SQL_DB_NAME: week_17_test
    depends_on:
      - kafka

  consumer:
    build: ./consumer
    container_name: consumer
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_TOPIC: users
      SQL_HOST: db
      SQL_USER: root
      SQL_PASSWORD: password
      SQL_DB_NAME: week_17_test
    depends_on:
      - kafka
      - mongo

  producer:
    build: ./producer
    container_name: cproducerr
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_TOPIC: users
      MONGO_DB: week_17_test
      MONGO_COLLECTION: orders
      MONGO_PORT: 27017
      MONGO_HOST: mongo
    depends_on:
      - kafka
      - mongo

 

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

volumes:
  mongo-data:
  kafka_data: